---
version: "3.7"

services:
  postgres:
    image: docker.io/postgres:12.2-alpine
    env_file:
      - ./env/local.env
    # environment:
    volumes:
      - postgres:/data/postgres
      - ./quarkus-bench/db/populate_test_user.pgsql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 1
        window: 30s
        condition: on-failure

networks:
  postgres:
    # driver: bridge

volumes:
  postgres:
