---
version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - quarkus-bench/db/populate_test_user.pgsql:/docker-entrypoint-initdb.d/1-populate_test_user.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    # driver: bridge

volumes:
    postgres:
    pgadmin: