---
version: "3.7"

services:
  postgres:
    image: docker.io/postgres:9.6.17
    # env_file:
    #   - ./env/local.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 1
        window: 30s
        condition: on-failure

networks:
  postgres:
    # driver: bridge

volumes:
  postgres:
