---
version: "3.7"

services:
  quarkus-bench:
    image: docker.io/quarkus/quarkus-bench-jvm:latest
    ports:
      - "9090:9090"
    environment:
     - NODE_ENV=production
     - POSTGRES_HOST=postgres
    env_file:
      - ./env/local.env    
    networks:
      - quarkus-net
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://127.0.0.1:9090/health/ready"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 1
        window: 30s
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 500M
        reservations:
          cpus: "0.50"
          memory: 500M
  postgres:
    image: docker.io/postgres:12.2-alpine
    env_file:
      - ./env/local.env
    # environment:
    volumes:
      - postgres:/data/postgres
      - ./quarkus-bench/db/populate_test_user.pgsql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "5432:5432"
    networks:
      - quarkus-net
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 1
        window: 30s
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 1G
        reservations:
          cpus: "0.50"
          memory: 1G
networks:
  quarkus-net:
    # driver: bridge

volumes:
  postgres:
